### ISSUE TITLE
Generated approval test file names can become too long

### ISSUE THREAD

**Issue by jnsn** [SimonCropp/XunitLogger#41]
#### Is the feature request related to a problem

On Windows we unfortunately still need to live with a maximum path length when creating files. This can quickly become a problem when using various build agents who create folders in folders to perform the builds, combined with long nested namespaces.

I am using this library because it works perfectly when combining xUnit with xBehave and ApprovalTests as xBehave's `[Scenario]` attribute uses the xUnit `[Theory]` attribute.

Given the following test class:

```cs
namespace Long.Namespace.Example.Tests
{
  public class Examples : XunitApprovalBase
  {
    public Examples(ITestOutputHelper output)
      : base(output) {}

    [Scenario]
    public void TestMethod()
    {
        "When I verify the contents"
          .x(() => Approvals.Verify("foo"));
    }
  }
}
```

When generating a unique test name, [the following snippet is used](https://github.com/SimonCropp/XunitLogger/blob/e3a42d6cb26e335e3c165be82857bf7a4efaeb7a/src/XunitLogger/LoggingContext_TestName.cs#L30):

```cs
var name = $"{method.TestClass.Class.Name}.{method.Method.Name}";
```

The `Name` property on the class returns the fully qualified type name (for non-generic parameters), or the simple type name (for generic parameters). (According to the [xUnit.TestClass.Name](https://github.com/xunit/abstractions.xunit/blob/f62f6907f7a209865fe9cbbd99612c0a28fe4bf5/src/xunit.abstractions/Reflection/ITypeInfo.cs#L52) documentation.)

This means that in my example the generated file name will be `Long.Namespace.Example.Tests.Examples.TestMethod.approved.json`.

When using xUnit's `[Fact]` attribute the correct class name is used for the file, but I loose the ability to use xBehave's scenario's or xUnit's `[Theory]` attributes.

If my file names get too long, I can't get them checked into git anymore because they are too long for git's path index, and even with a shorter name my build server freaks out because it can created folders like `D:\agent-1\working-dir\project\s\...` were I already lose a lot of characters before the file is even generated.

#### Describe the solution

When generating the unique test name, only the class name should be used because the files will be in the correct folder anyway. Or allow the use of the test display name or another override.

**Comment by SimonCropp** [comment]
as an aside, i dont hit this since namespaces are usually redundant for tests and hence i dont use them. 

as for your proposal, how would u handle a conflict? ie multiple files in the same dir with the same name but diff namespaces?

**Comment by jnsn** [comment]
You could always allow us to override the default behavior (the current behavior) to counter this. 

In my case, I always have a physical folder per namespace too, so I won't have multiple files with the same name in the same folder. 

Even then, since the file name contains both the class name and the method name (with optional parameters), I think the changes are low enough for this to be an edge-case which can be bypassed by overriding the generated class name for a single test.

**Comment by SimonCropp** [comment]
This is now deployed. NuGet may take some time to make it available for download.
