### ISSUE TITLE
Theory approval file names

### ISSUE THREAD

**Issue by kenlefeb** [SimonCropp/XunitLogger#60]
I was excited when I discovered your package and saw that you support xUnit Theory approvals! Unfortunately, I've been trying to get it working and haven't had any success. Perhaps there is something really silly that I'm doing incorrectly, but I _think_ I am running exactly what your documentation says should work:

```
using ApprovalTests;
using Xunit;
using Xunit.Abstractions;

namespace Tests
{
	public class TheoryTests : XunitLoggingBase
	{
		public TheoryTests(ITestOutputHelper output) : base(output) { }

		[Theory]
		[InlineData("Foo")]
		[InlineData(9)]
		[InlineData(true)]
		public void Theory(object value)
		{
			Approvals.Verify(value);
		}
	}
}
```
I do have a couple of assembly attributes in another file, just in case those might be causing a problem:
```
using ApprovalTests.Namers;
using ApprovalTests.Reporters;

[assembly: UseReporter(typeof(DiffReporter))]
[assembly: UseApprovalSubdirectory("approvals")]
```
The problem I'm seeing is that the names are colliding (so two of the three tests fail), and I'm sure I could use one of the NamerFactory methods to solve this myself, but my understanding is that I shouldn't have to, correct?

My received file looks like this (I assume it's being written three times):

...\Tests\approvals\TheoryTests.Theory.received.txt

Just for completeness, here are the only references I have in my project:

```
  <ItemGroup>
    <PackageReference Include="FluentAssertions.Json" Version="5.3.0" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.4.0" />
    <PackageReference Include="xunit" Version="2.4.1" />
    <PackageReference Include="Xunit.ApprovalTests" Version="4.5.0" />
    <PackageReference Include="xunit.runner.visualstudio" Version="2.4.1" />
  </ItemGroup>
```
Can you see what I'm doing wrong? How would you recommend that I troubleshoot this next?

**Comment by SimonCropp** [comment]
seems you are missing the base class? https://github.com/SimonCropp/XunitLogger#usage

**Comment by kenlefeb** [comment]
LOL. I did forget that in _this_ class, but I had it in the original test class. I created a new class so I could use just your sample test to compose this issue for you.

My Visual Studio is doing an update right now, but later on I'll add that back in just to be sure, and try again.

Thanks for such a speedy response!

**Comment by SimonCropp** [comment]
BTW have u seen this https://github.com/SimonCropp/ObjectApproval ?

**Comment by kenlefeb** [comment]
OK. I just verified that I'm still having my issues with the base class, and I've edited my original post.

About ObjectApproval, yes. I have used ObjectApproval for a long time! In fact, I was using it in these tests, until I started removing stuff to try to figure out why I couldn't get Theory to work. :) 

When it comes to your ObjectApproval package, I am an _uberfan_.

**Comment by SimonCropp** [comment]
can u dump your sample solution in a public github repo and i will debug it

**Comment by kenlefeb** [comment]
Sure thing... here you go!

https://github.com/kenlefeb/Theories

I really appreciate your help with this. I know you weren't planning to help me out, today, so take your time and enjoy your weekend, too! :)

**Comment by SimonCropp** [comment]
ok this was a bug. i wasnt checking the assembly for the attribute. deployed a fix to nuget. also your base class needs to be `XunitApprovalBase`

**Comment by kenlefeb** [comment]
I will test it out right away... thanks so much!!!

**Comment by SimonCropp** [comment]
no worries, BTW i now have a github sponsors page if you or your employer wants to say thanks https://github.com/sponsors/simoncropp
